/*
 * Copyright 2026, Kevin Adams <kevinadams05@gmail.com>. All rights reserved.
 * Distributed under the terms of the MIT License.
 */
#ifndef SERVER_CONNECTION_LISTENER_H
#define SERVER_CONNECTION_LISTENER_H


#include "core/ChatMessage.h"
#include "core/UserRecord.h"


namespace hitux {


/** What a ServerConnection is currently doing. */
enum ConnectionState
{
	CONNECTION_DISCONNECTED = 0,
	CONNECTION_CONNECTING,
	CONNECTION_CONNECTED
};


/** The one and only way a ServerConnection talks back to a front-end.
  *
  * Every method here is invoked on the thread that owns the ICallbackMechanism the
  * connection was constructed with -- for the Qt front-end that is the GUI thread,
  * so implementations may touch widgets directly without any further locking.
  *
  * Keeping this an abstract interface rather than a set of Qt signals is what lets
  * libhitux-core stay free of any toolkit dependency.
  */
class ServerConnectionListener
{
public:
	virtual ~ServerConnectionListener() {}

	/** The connection moved between disconnected, connecting and connected.
	  * @param state the state just entered
	  */
	virtual void ConnectionStateChanged(ConnectionState state) = 0;

	/** The server told us our own session ID, which happens shortly after connecting
	  * and is a prerequisite for sending chat.
	  * @param sessionId our session ID on this server
	  * @param hostName the server's idea of its own host name
	  */
	virtual void LocalSessionIdAssigned(const muscle::String& sessionId,
		const muscle::String& hostName) = 0;

	/** A user appeared, or a user we already knew published something new.
	  * @param user the user's complete current state
	  * @param isNewUser true the first time we see this session ID
	  */
	virtual void UserUpdated(const UserRecord& user, bool isNewUser) = 0;

	/** A user disconnected from the server.
	  * @param user the user's last known state, still valid for this call only
	  */
	virtual void UserLeft(const UserRecord& user) = 0;

	/** A line arrived for the chat log -- from a peer, or generated by the connection
	  * itself to report something to the user.
	  * @param message the line
	  */
	virtual void ChatMessageReceived(const ChatMessage& message) = 0;

	/** A peer answered a ping we sent them.
	  * @param user the peer that replied
	  * @param roundTripMicroseconds how long the round trip took
	  * @param peerVersion the client version string the peer reported, may be empty
	  */
	virtual void PingReplyReceived(const UserRecord& user, uint64 roundTripMicroseconds,
		const muscle::String& peerVersion) = 0;
};


}  // namespace hitux


#endif  // SERVER_CONNECTION_LISTENER_H
