/*
 * Copyright 2026, Kevin Adams <kevinadams05@gmail.com>. All rights reserved.
 * Distributed under the terms of the MIT License.
 */
#ifndef SERVER_CONNECTION_LISTENER_H
#define SERVER_CONNECTION_LISTENER_H


#include "core/ChatMessage.h"
#include "core/FileResult.h"
#include "core/UserRecord.h"


namespace hitux {


/** What a ServerConnection is currently doing. */
enum ConnectionState
{
	CONNECTION_DISCONNECTED = 0,
	CONNECTION_CONNECTING,
	CONNECTION_CONNECTED
};


/** The one and only way a ServerConnection talks back to a front-end.
  *
  * Every callback names the connection it came from. That is not decoration:
  * session IDs, user lists and query results are all scoped to one connection,
  * so a listener that cannot tell two connections apart cannot correctly hold
  * more than one -- which is exactly the groundwork multi-server needs.
  *
  * Every method here is invoked on the thread that owns the ICallbackMechanism the
  * connection was constructed with -- for the Qt front-end that is the GUI thread,
  * so implementations may touch widgets directly without any further locking.
  *
  * Keeping this an abstract interface rather than a set of Qt signals is what lets
  * libhitux-core stay free of any toolkit dependency.
  */
class ServerConnection;


class ServerConnectionListener
{
public:
	virtual ~ServerConnectionListener() {}

	/** The connection moved between disconnected, connecting and connected.
	  * @param state the state just entered
	  */
	virtual void ConnectionStateChanged(ServerConnection* connection,
		ConnectionState state) = 0;

	/** The server told us our own session ID, which happens shortly after connecting
	  * and is a prerequisite for sending chat.
	  * @param sessionId our session ID on this server
	  * @param hostName the server's idea of its own host name
	  */
	virtual void LocalSessionIdAssigned(ServerConnection* connection,
		const muscle::String& sessionId, const muscle::String& hostName) = 0;

	/** A user appeared, or a user we already knew published something new.
	  * @param user the user's complete current state
	  * @param isNewUser true the first time we see this session ID
	  */
	virtual void UserUpdated(ServerConnection* connection,
		const UserRecord& user, bool isNewUser) = 0;

	/** A user disconnected from the server.
	  * @param user the user's last known state, still valid for this call only
	  */
	virtual void UserLeft(ServerConnection* connection,
		const UserRecord& user) = 0;

	/** A line arrived for the chat log -- from a peer, or generated by the connection
	  * itself to report something to the user.
	  * @param message the line
	  */
	virtual void ChatMessageReceived(ServerConnection* connection,
		const ChatMessage& message) = 0;

	/** A file matching the running query appeared, or an already-known one was
	  * re-published with new details.
	  *
	  * Results keep arriving for as long as the query runs, so this is called
	  * long after the initial sweep finishes.
	  *
	  * @param result the file
	  */
	virtual void QueryResultAdded(ServerConnection* connection,
		const FileResult& result) = 0;

	/** A file stopped being shared, or its sharer left.
	  * @param sessionId who was sharing it
	  * @param fileName the file that went away
	  */
	virtual void QueryResultRemoved(ServerConnection* connection,
		const muscle::String& sessionId, const muscle::String& fileName) = 0;

	/** Every result was dropped, because the query changed or stopped. */
	virtual void QueryResultsCleared(ServerConnection* connection) = 0;

	/** The initial sweep of a query started or finished.
	  *
	  * False does not mean no more results are coming -- it means the server has
	  * finished sending what it already had. The subscription stays live.
	  *
	  * @param isSweeping true while the server is still sending existing matches
	  */
	virtual void QuerySweepStateChanged(ServerConnection* connection,
		bool isSweeping) = 0;

	/** A peer answered a ping we sent them.
	  * @param user the peer that replied
	  * @param roundTripMicroseconds how long the round trip took
	  * @param peerVersion the client version string the peer reported, may be empty
	  */
	virtual void PingReplyReceived(ServerConnection* connection,
		const UserRecord& user, uint64 roundTripMicroseconds,
		const muscle::String& peerVersion) = 0;
};


}  // namespace hitux


#endif  // SERVER_CONNECTION_LISTENER_H
